# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbffe65dcb70e767c6a18e026a8058e28ba130c96e7313ab184a83d3181dfcd801a2fb4abbd91e339037effb9792e4701fa801f2bf8a22769edf4dc5750656ce

test:
  secret_key_base: 658b684986b1700319239b08444396956a841d87132965d55ee93c94fc6215092e0a202fe6347d066e0088846b3f4fbbeb401270d7daaabf564e999d6880b6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
